// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"flamingo.me/flamingo/v3/framework/web"
	mock "github.com/stretchr/testify/mock"
)

// NewService creates a new instance of Service. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewService(t interface {
	mock.TestingT
	Cleanup(func())
}) *Service {
	mock := &Service{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// Service is an autogenerated mock type for the Service type
type Service struct {
	mock.Mock
}

type Service_Expecter struct {
	mock *mock.Mock
}

func (_m *Service) EXPECT() *Service_Expecter {
	return &Service_Expecter{mock: &_m.Mock}
}

// Generate provides a mock function for the type Service
func (_mock *Service) Generate(session *web.Session) string {
	ret := _mock.Called(session)

	if len(ret) == 0 {
		panic("no return value specified for Generate")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func(*web.Session) string); ok {
		r0 = returnFunc(session)
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// Service_Generate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Generate'
type Service_Generate_Call struct {
	*mock.Call
}

// Generate is a helper method to define mock.On call
//   - session *web.Session
func (_e *Service_Expecter) Generate(session interface{}) *Service_Generate_Call {
	return &Service_Generate_Call{Call: _e.mock.On("Generate", session)}
}

func (_c *Service_Generate_Call) Run(run func(session *web.Session)) *Service_Generate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *web.Session
		if args[0] != nil {
			arg0 = args[0].(*web.Session)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_Generate_Call) Return(s string) *Service_Generate_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *Service_Generate_Call) RunAndReturn(run func(session *web.Session) string) *Service_Generate_Call {
	_c.Call.Return(run)
	return _c
}

// IsValid provides a mock function for the type Service
func (_mock *Service) IsValid(request *web.Request) bool {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for IsValid")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*web.Request) bool); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Service_IsValid_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValid'
type Service_IsValid_Call struct {
	*mock.Call
}

// IsValid is a helper method to define mock.On call
//   - request *web.Request
func (_e *Service_Expecter) IsValid(request interface{}) *Service_IsValid_Call {
	return &Service_IsValid_Call{Call: _e.mock.On("IsValid", request)}
}

func (_c *Service_IsValid_Call) Run(run func(request *web.Request)) *Service_IsValid_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *web.Request
		if args[0] != nil {
			arg0 = args[0].(*web.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_IsValid_Call) Return(b bool) *Service_IsValid_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Service_IsValid_Call) RunAndReturn(run func(request *web.Request) bool) *Service_IsValid_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidHeader provides a mock function for the type Service
func (_mock *Service) IsValidHeader(request *web.Request) bool {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for IsValidHeader")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*web.Request) bool); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Service_IsValidHeader_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidHeader'
type Service_IsValidHeader_Call struct {
	*mock.Call
}

// IsValidHeader is a helper method to define mock.On call
//   - request *web.Request
func (_e *Service_Expecter) IsValidHeader(request interface{}) *Service_IsValidHeader_Call {
	return &Service_IsValidHeader_Call{Call: _e.mock.On("IsValidHeader", request)}
}

func (_c *Service_IsValidHeader_Call) Run(run func(request *web.Request)) *Service_IsValidHeader_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *web.Request
		if args[0] != nil {
			arg0 = args[0].(*web.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_IsValidHeader_Call) Return(b bool) *Service_IsValidHeader_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Service_IsValidHeader_Call) RunAndReturn(run func(request *web.Request) bool) *Service_IsValidHeader_Call {
	_c.Call.Return(run)
	return _c
}

// IsValidPost provides a mock function for the type Service
func (_mock *Service) IsValidPost(request *web.Request) bool {
	ret := _mock.Called(request)

	if len(ret) == 0 {
		panic("no return value specified for IsValidPost")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(*web.Request) bool); ok {
		r0 = returnFunc(request)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// Service_IsValidPost_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsValidPost'
type Service_IsValidPost_Call struct {
	*mock.Call
}

// IsValidPost is a helper method to define mock.On call
//   - request *web.Request
func (_e *Service_Expecter) IsValidPost(request interface{}) *Service_IsValidPost_Call {
	return &Service_IsValidPost_Call{Call: _e.mock.On("IsValidPost", request)}
}

func (_c *Service_IsValidPost_Call) Run(run func(request *web.Request)) *Service_IsValidPost_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *web.Request
		if args[0] != nil {
			arg0 = args[0].(*web.Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *Service_IsValidPost_Call) Return(b bool) *Service_IsValidPost_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *Service_IsValidPost_Call) RunAndReturn(run func(request *web.Request) bool) *Service_IsValidPost_Call {
	_c.Call.Return(run)
	return _c
}
