language: go

go:
  - 1.x
  - 1.13.x

env:
  - GO111MODULE=on

install: true

script:
  - go run golang.org/x/lint/golint -set_exit_status $(go list ./...)
  - go test -v -vet=all ./...
  - go test -v -race ./...
